### ISSUE TITLE
Trying to load plugin via Glue

### ISSUE THREAD

**Issue by dennismonsewicz** [peteut/hapi-shelf#6]
I am attempting to load this plugin using Glue (https://github.com/hapijs/glue), but it cannot load the models because it is loading the models from within the `node_modules` directory instead of using the `process.cwd()`

**Comment by peteut** [comment]
Good catch, thanks!

**Comment by dennismonsewicz** [comment]
No problem!! Do you know when this issue might be resolved? I don't know enough about `ramda` or I'd attempt to help out :frowning:

**Comment by peteut** [comment]
I'm aiming to fix it this weekend.

**Comment by dennismonsewicz** [comment]
Awesome, thank you!!

On Fri, Jul 31, 2015 at 1:03 PM, Alain Péteut notifications@github.com
wrote:

> I'm aiming to fix it this weekend.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/peteut/hapi-shelf/issues/6#issuecomment-126752816.

## 

Dennis Monsewicz Jr.C: (256) 339-8716dennismonsewicz.com

**Comment by peteut** [comment]
Thanks alot, it's much cleaner now!
